### ISSUE TITLE
Secret key should not be stored in repository

### ISSUE THREAD

**Issue by R2RT** [0Friend0/AlleBot#1]
```
app.config['SECRET_KEY'] = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```

By definition secret key is secret, so it should not be hardcoded in sources.

There are several ways to do it, but in this the easiest one is using environment variable. (Same way as you provide `FLASK_APP=AlleBotWebsite.py`).

**Comment by 0Friend0** [comment]
FIXED
