### ISSUE TITLE
__pycache__ should not be commited (.gitignore)

### ISSUE THREAD

**Issue by R2RT** [0Friend0/AlleBot#2]
This directory contains platform-specific temporary files generated from Python compilation.

1) .pyc files generated on Windows may not be reused on Linux, etc.
2) .pyc files are regenerated whenever you chance your source code

There is no need to keep them in repository, since every user may need other ones and technically, they only duplicate information that is provided by source files already. 

In programming, duplication is considered bad (`functions` > `code copying/duplication`, etc.), since you have to manually maintain that both copies are synced.

**Comment by 0Friend0** [comment]
FIXED
