### ISSUE TITLE
Files naming is not consistent

### ISSUE THREAD

**Issue by R2RT** [0Friend0/AlleBot#8]
Obviously, there are as many approaches as developers on the world. But the common one and easy to maintain is to simply keep each class in independent files named after class.

Thus, `functions.py` -> `Application.py`

Once this gets messy, you start grouping classes into directories/modules.

For example, if you add more forms (like in current `forms.py`) you can create directory `forms` and have `forms/Prices.py`, `forms/MaxPages.py` etc.

**Comment by 0Friend0** [comment]
FIXED
