### ISSUE TITLE
`global item_count` is code smell

### ISSUE THREAD

**Issue by R2RT** [0Friend0/AlleBot#9]
I've already shown my hate to singletons/shared class state in #6 and #7. Well, `global` is even worse :P

`global`s are easy to track and understand in small projects, but very opposite in larger ones.

There usually are better ways to handle it, but I can't say what is the solution for Flask.

This [answer ](https://stackoverflow.com/a/53152394/5945883) to this [question](https://stackoverflow.com/questions/32815451/are-global-variables-thread-safe-in-flask-how-do-i-share-data-between-requests) about sessions sounds reasonable.

**Comment by 0Friend0** [comment]
FIXED
